services:
  - type: web
    name: zodiac-sign-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false
      - key: USER_COLLECTION
        sync: false
      - key: PRED_COLLECTION
        sync: false
